cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

groups/urls.py
""""Groups UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'groups.views.home', name='home'),
    
    url(r'^new/group', 'groups.views.new_group', name='new_group'),
    url(r'^delete/group/(?P<name>.*)$', 'groups.views.delete_group', name='delete_group'),
    url(r'^edit/group/(?P<name>.*)$', 'groups.views.edit_group', name='edit_group'),
    
    url(r'^rm/(?P<name>.*)/(?P<uname>.*)$', 'groups.views.rm_user', name='rm_user'),
    url(r'^add/(?P<name>.*)$', 'groups.views.add_user', name='add_user'),

    url(r'^(?P<name>.*)$', 'groups.views.group_view', name='view'),
    

]

indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    # All routes from here are to be re-routed to the agent by using
    # nginx to re-route calls as an internal redirect
    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/models.py
from django.db import models

# Create your models here.

groups/forms.py
from django import forms

class GroupForm(forms.Form):

    name = forms.CharField(label='Username', max_length=100, required=True)
 
class GroupAddForm(forms.Form):
 
    def __init__(self, users, *args, **kwargs):
        super(GroupAddForm, self).__init__(*args, **kwargs)
        self.fields['users'] = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                         choices=users)

groups/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.contrib import messages
from django.core.exceptions import PermissionDenied

from groups.forms import (
    GroupForm,
    GroupAddForm
)
from indigo.models import (
    Group,
    User
)


@login_required
def add_user(request, name):
    group = Group.find(name)
    if not group:
        raise Http404
    if not request.user.administrator:
        raise PermissionDenied
    users = [(u.name, u.name) for u in User.objects.all()
             if not group.name in u.groups]
    if request.method == 'POST':
        form = GroupAddForm(users, request.POST)
        if form.is_valid():
            data = form.cleaned_data
            new_users = data.get('users', [])
            added, not_added, already_there = group.add_users(new_users)
            if added:
                msg = "{} has been added to the group '{}'".format(", ".join(added),
                                                                   group.name)
                group.update(username=request.user.name)
            else:
                msg = "No user has been added to the group '{}'".format(group.name)
            messages.add_message(request, messages.INFO, msg)
            return redirect('groups:view', name=name)
            
    else:
        form = GroupAddForm(users)

    ctx = {
        "group": group,
        "form": form,
        "users": users
    }
    return render(request, 'groups/add.html', ctx)


@login_required
def delete_group(request, name):
    group = Group.find(name)
    if not group:
        raise Http404
    if not request.user.administrator:
        raise PermissionDenied
    if request.method == "POST":
        group.delete(username=request.user.name)
        messages.add_message(request, messages.INFO,
                             "The group '{}' has been deleted".format(group.name))
        return redirect('groups:home')

    # Requires delete on user
    ctx = {
        "group": group,
    }
    return render(request, 'groups/delete.html', ctx)


@login_required
def edit_group(request, name):
    # Requires edit on user
    group = Group.find(name)
    if not group:
        raise Http404()

    if not request.user.administrator:
        raise PermissionDenied

    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            group.update(name=data['name'],
                         username=request.user.name)
            return redirect('groups:home')
    else:
        initial_data = {'name': group.name}
        form = GroupForm(initial=initial_data)

    ctx = {
        "form": form,
        "group": group,
    }

    return render(request, 'groups/edit.html', ctx)


@login_required
def group_view(request, name):
    # argument is the name in Cassandra
    group = Group.find(name)
    if not group:
        return redirect('groups:home')
        #raise Http404
    ctx = {
        "user": request.user,
        "group_obj": group,
        "members": group.get_usernames()
    }
    return render(request, 'groups/view.html', ctx)


@login_required
def home(request):
    # TODO: Order by groupname
    group_objs = list(Group.objects.all())

    paginator = Paginator(group_objs, 10)
    page = request.GET.get('page')
    try:
        groups = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        groups = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        groups = paginator.page(paginator.num_pages)

    ctx = {
        "user": request.user,
        "groups": groups,
        "group_count": len(group_objs)
    }
    return render(request, 'groups/index.html', ctx)


@login_required
def new_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            group = Group.create(name=data.get("name"),
                                 username=request.user.name)
            messages.add_message(request, messages.INFO,
                             "The group '{}' has been created".format(group.name))
            return redirect('groups:home')
    else:
        form = GroupForm()
    ctx = {
        "form": form,
    }
    
    return render(request, 'groups/new.html', ctx)


def notify_agent(user_id, event=""):
    from nodes.client import choose_client
    client = choose_client()
    client.notify(user_id, event)


@login_required
def rm_user(request, name, uname):
    group = Group.find(name)
    user = User.find(uname)
    if not request.user.administrator:
        raise PermissionDenied
    if user and group:
        removed, not_there, not_exist = group.rm_user(uname)
        if removed:
            msg = "'{}' has been removed from the group '{}'".format(uname,
                                                                   name)
        elif not_there:
            msg = "'{}' isn't in the group '{}'".format(uname, name)
        elif not_exist:
            msg = "'{}' doesn't exist".format(uname)
        messages.add_message(request, messages.INFO, msg)
    else:
        raise Http404
    return redirect('groups:view', name=name)

groups/templates/groups/add.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}

{% block title %}Add user to group{% endblock title %}

{% block main_content %}

<h2>Add user(s)
    <a class="pull-right btn btn-default" href="{% url 'groups:view' name=group.name %}">
    &laquo; Back to Group
    </a>
    </h2>
<hr/>

{% include "groups/add_form.html" with form=form action='add' group=group users=users%}

{% endblock main_content %}

groups/templates/groups/add_form.html
<!-- 
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}
 -->
{% if action == 'add' %}
    {% url 'groups:add_user' name=group.name as post_url %}
{% endif %}

<form id="addForm" method="POST" action="{{post_url}}" novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    
<!--     {{ form }} -->
    
    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="name" class="control-label">User list</label>
    </div>
    <p>
        <select id="select_add_user_form" name="users" form="addForm" multiple
                style="width:100px;height:200px">
            {% for uname, _ in users %}
              <option value="{{uname}}">{{uname}} </option>
            {% endfor %}
        </select>
    </p>

    
    
    <button type="submit" class="btn btn-success btn-block">Add</button>
</form>

groups/templates/groups/delete.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}

{% block title %}Delete Group - {{group.name}}{% endblock title %}

{% block main_content %}

    <h2>Delete Group - {{group.name}}</h2>

    <br/><br/>

    <div style="text-align:center; margin-top: 20px;">
        <div style='font-size: 1.5em'>
        Are you sure you wish to delete group {{group.name}}?
        </div>

        <form action="{% url 'groups:delete_group' name=group.name %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Delete this group</button>
            <a href="{% url 'groups:home' %}" class="btn btn-lg btn-success">Cancel</a>
        </form>

    </div>
{% endblock main_content %}

groups/templates/groups/edit.html
{% extends "archive/base.html" %}

{% block title %}Edit Group - {{group.name}}{% endblock title %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}

{% block main_content %}

<h2>Edit Group - {{group.name}}
    <a class="pull-right btn btn-default" href="{% url 'groups:home' %}">
    &laquo; Back to group management
    </a>
</h2>
<hr/>

{% include "groups/group_form.html" with form=form group=group action='edit'%}

{% endblock main_content %}

groups/templates/groups/group_form.html
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}

{% if action == 'edit' %}
    {% url 'groups:edit_group' name=group.name as post_url %}
{% else %}
    {% url 'groups:new_group' as post_url %}
{% endif %}

<form id="loginForm" method="POST" action="{{post_url}}" novalidate="novalidate" enctype="multipart/form-data">
    {% csrf_token %}
    
<!--     {{ form }} -->
    
    <div class="form-group {% if form.errors.name %}has-error{% endif %}">
        <label for="name" class="control-label">Group name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{form.name.value|default:''}}"  title="Enter the group name" placeholder="Name of group">
    </div>
    
    <button type="submit" class="btn btn-success btn-block">Save</button>
</form>

groups/templates/groups/grouptab.html
{% load gravatar %}

<div class="col-md-3" >
    <table width="100%" border="0" class="table user-tab" style="table-layout:fixed;" cellpadding="0" cellspacing="0">
        <tr>
            <td>
            {% gravatar group.name 20 %}
            </td>
            <td>
              <a href="{% url 'groups:view' name=group.name %}">
                {{ group.name }}
              </a>
            </td>
            {% if user.administrator %}
              <td valign="top" align="left">
                  <a href="{% url 'groups:delete_group' name=group.name %}">
                  <i class="blue-icon glyphicon glyphicon-remove-circle"></i>
                  </a>
              </td>
            {% endif %}
        </tr>
    </table>
</div>

groups/templates/groups/index.html
{% extends "base.html" %}


{% block title %}Groups{% endblock title %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}


{% block main_content %}
    <h2>Groups ({{ group_count }})</h2><hr/>

	{% if user.administrator %}
	<div class="row">
	  <div class="pull-right">
	    <a class="btn btn-sm btn-success" href="{% url 'groups:new_group' %}">Add new group</a>
	    
	  </div>
	</div>
	<hr/>
	{% endif %}

    {% for group in groups %}
        {% include "groups/grouptab.html" with group=group%}
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if groups.has_previous %}
                <a href="?page={{ groups.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ groups.number }} of {{ groups.paginator.num_pages }}.
            </span>

            {% if groups.has_next %}
                <a href="?page={{ groups.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>


{% endblock main_content %}

groups/templates/groups/new.html
{% extends "archive/base.html" %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}

{% block title %}New Group{% endblock title %}

{% block main_content %}

<h2>New Group
    <a class="pull-right btn btn-default" href="{% url 'groups:home' %}">
    &laquo; Back to Group list
    </a>
    </h2>
<hr/>

{% include "groups/group_form.html" with form=form action='new' %}

{% endblock main_content %}

groups/templates/groups/view.html
{% extends "base.html" %}
{% load gravatar %}

{% block title %}Groups - {{group_obj.name}}{% endblock title %}

{% block sidebar %}
    {% include "snippets/sidenav.html" with active="groups" %}
{% endblock sidebar %}


{% block main_content %}
    <h2>{% gravatar group_obj.name 40 %} {{ group_obj.name }}</h2>

    <hr/>
    <h3>Members</h3>

    <div>
        
        <ul>
        {% for member_name in members %}
            <li>
              <a href="{% url 'users:view' name=member_name %}">{{ member_name }}</a>
                {% if user.administrator %}
                  <a href="{% url 'groups:rm_user' name=group_obj.name uname=member_name %}">
                    <i class="blue-icon glyphicon glyphicon-remove-circle"></i>
                  </a>
                {% endif %}
            </li>
        {% endfor %}
        {% if user.administrator %}
          <li>
            <a href="{% url 'groups:add_user' name=group_obj.name %}">Add user</a>
          </li>
        {% endif %}
        </ul>
    </div>


{% endblock main_content %}