archive/urls.py
"""Archive URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'archive.views.home', name='home'),
    url(r'^search$', 'archive.views.search', name='search'),
    url(r'^search2$', 'archive.views.search2', name='search2'),

    url(r'^resource(?P<path>.*)$', 'archive.views.view_resource', name='resource_view'),
    url(r'^new/collection(?P<parent>.*)$', 'archive.views.new_collection', name='new_collection'),
    url(r'^edit/collection(?P<path>.*)$', 'archive.views.edit_collection', name='edit_collection'),
    url(r'^delete/collection(?P<path>.*)$', 'archive.views.delete_collection', name='delete_collection'),

    url(r'^new/resource(?P<parent>.*)$', 'archive.views.new_resource', name='new_resource'),
    url(r'^edit/resource(?P<path>.*)$', 'archive.views.edit_resource', name='edit_resource'),
    url(r'^delete/resource(?P<path>.*)$', 'archive.views.delete_resource', name='delete_resource'),

    url(r'^view(?P<path>.*)$', 'archive.views.view_collection', name='view'),
    url(r'^download(?P<path>.*)$', 'archive.views.download', name='download'),
    url(r'^preview(?P<path>.*)$', 'archive.views.preview', name='preview'),
]

cdmi/urls.py
""""CDMI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import (
    url,
    include
)
from rest_framework.urlpatterns import format_suffix_patterns
from cdmi import views


urlpatterns = [
   url(r'^cdmi_capabilities(?P<path>.*)$', 'cdmi.views.capabilities', name='capabilities'),
   url(r'^cdmi_objectid/(?P<id>.*)$', 'cdmi.views.crud_id', name='crud_id'),
   
   url(r'^(?P<path>.*)$', views.CDMIView.as_view(), name="api_cdmi"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

indigo_ui/urls.py
""""Indigo UI URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'indigo_ui.views.home', name='home'),
    url(r'^archive/', include('archive.urls', namespace="archive")),
    url(r'^node/', include('nodes.urls', namespace="nodes")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^groups/', include('groups.urls', namespace="groups")),
    url(r'^activity/', include('activity.urls', namespace="activity")),

    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    # All routes from here are to be re-routed to the agent by using
    # nginx to re-route calls as an internal redirect
    url(r'^api/cdmi/', include('cdmi.urls', namespace="cdmi")),
    url(r'^api/admin/', include('admin.urls', namespace="admin")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nodes/urls.py
"""Node URLs

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nodes.views.home', name='home'),
    url(r'^new$', 'nodes.views.new', name='new'),
    url(r'^(?P<id>.*)/edit$', 'nodes.views.edit', name='edit'),
    url(r'^(?P<id>.*)/check$', 'nodes.views.check', name='check'),
    url(r'^(?P<id>.*)/log$', 'nodes.views.logview', name='logview'),
    url(r'^(?P<id>.*)/metrics$', 'nodes.views.metrics', name='metrics'),
]

archive/models.py
"""Archive Models

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.db import models

archive/forms.py
"""Archive Forms

Copyright 2015 Archive Analytics Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from django import forms
import json

from indigo.metadata import (
    get_collection_validator,
    get_resource_validator
)

from archive.widgets import JsonPairInputs


def get_groups():
    from indigo.models import Group
    return [(u'AUTHENTICATED@', 'authenticated@'),
            (u'ANONYMOUS@', 'anonymous@')] + [(g.name,g.name,) for g in Group.objects.all()]

class CollectionForm(forms.Form):
    groups = get_groups

    metadata = forms.CharField(label="Metadata", required=False,
                               widget=JsonPairInputs())
    read_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    write_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    edit_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    delete_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)

    def clean_metadata(self):
        data = self.cleaned_data['metadata']
        dct = {}
        for l in json.loads(data):
            dct[l[0]] = l[1]

        ok, errs = get_collection_validator().validate(dct)
        if not ok:
            raise forms.ValidationError([forms.ValidationError(e) for e in errs])
        return data


class CollectionNewForm(CollectionForm):
    name = forms.CharField(label='Collection name', max_length=100, required=True)

class ResourceForm(forms.Form):
    groups = get_groups

    metadata = forms.CharField(label="Metadata", required=False,
                               widget=JsonPairInputs())
    read_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    write_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    edit_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)
    delete_access = forms.MultipleChoiceField(required=False,
                                    widget=forms.CheckboxSelectMultiple(),
                                    choices=groups,)

    def clean_metadata(self):
        data = self.cleaned_data['metadata']
        dct = {}
        for l in json.loads(data):
            dct[l[0]] = l[1]

        ok, errs = get_resource_validator().validate(dct)
        if not ok:
            raise forms.ValidationError([forms.ValidationError(e) for e in errs])
        return data


class ResourceNewForm(ResourceForm):
    name = forms.CharField(label='Item name', max_length=100, required=True)
    file = forms.FileField(required=True)

archive/templates/archive/snippets/collection.html
<ol class="breadcrumb">
  <li><a href="{% url 'archive:view' path="" %}">Home</a></li>
  {% for coll,full in collection_paths %}
    {% if forloop.last %}
        <li class="active">{{coll}}</li>
    {% else %}
        <li><a href="{% url 'archive:view' path=full %}">{{coll}}</a></li>
    {% endif %}
  {% endfor %}
</ol>


{% include "archive/snippets/metadata.html" with metadata=collection.metadata path=collection.path label='success' %}
<hr/>

{% if collection.can_write %}
<div class="row">
  <div class="pull-right">
    <a class="btn btn-sm btn-success" href="{% url 'archive:new_collection' parent=collection.path %}">Add new collection</a>
    &nbsp;&nbsp;
    <a class="btn btn-sm btn-success" href="{% url 'archive:new_resource' parent=collection.path %}">Add new item </a>
  </div>
</div>
<hr/>
{% endif %}


{% for c in children_c %}
  {% include "archive/snippets/collection_entry.html" with collection=c %}
{% endfor %}

{% for r in children_r %}
  {% include "archive/resource/resource_entry.html" with resource=r %}
{% endfor %}

{% if empty %}
  This collection is empty
{% endif %}

<hr/>

archive/templates/archive/snippets/collection_entry.html
<div class="collection-entry row">

    <div class="col-md-12">
      {% if collection.can_delete %}
        <a href="{% url 'archive:delete_collection' path=collection.path %}">
        <i class="blue-icon glyphicon glyphicon glyphicon-remove-circle"></i>
        &nbsp;&nbsp;
        </a>
      {% endif %}
      {% if collection.can_read %}
      <i class="blue-icon glyphicon glyphicon-folder-open"></i>
      &nbsp;&nbsp;
      <a href="{% url 'archive:view' path=collection.path %}">
          {{ collection.name }}
      </a>
      {% else %}
        <span style="color: #999;">
        <i class="gray-icon glyphicon glyphicon glyphicon-folder-close"></i>&nbsp;&nbsp;
          {{ collection.name }}
        </span>
      {% endif %}
    </div>

</div>

{% if collection.metadata %}
<div class="row" style="margin-top: 10px;">
    {% if collection.can_read %}
        <div class="col-md-12">
            {% include "archive/snippets/metadata.html" with metadata=collection.metadata label='default'%}
        </div>
    {% endif %}
</div>
{% endif %}

{# Hidden fields are showing debug information from search results #}
<span style="display:none;">
    <span>Hit count: {{ c.hit_count }}</span>
</span>
<hr/>

archive/templates/archive/snippets/collection_form.html
{% if form.errors %}
    <div class="alert alert-danger">
    Please correct the problem in the form below.
    </div>
{% endif %}



{% if action == 'edit' %}
    {% url 'archive:edit' uuid=collection.uuid as post_url %}
{% else %}
    {% url 'archive:new' parent=collection.uuid as post_url %}
{% endif %}


<form id="loginForm" method="POST" action="{{post_url}}" novalidate="novalidate">
    {% csrf_token %}
    
    {% if action == 'new' %}    
      <div class="form-group {% if form.errors.name %}has-error{% endif %}">
          <label for="name" class="control-label">Name</label>
          <input type="text" class="form-control" id="name" name="name" value="{{form.name.value|default:''}}"  title="Enter the collection name" placeholder="Name of collection">
      </div>
    {% endif %}

    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-md-3">
            <strong>Read permission</strong>
            <div class="checkbox">
                {{form.read_access}}
            </div>
        </div>
        <div class="col-md-3 left-border">
            <strong>Write permission</strong>
            <div class="checkbox">
                {{form.write_access}}
            </div>
        </div>
    </div>
    <h4>Metadata</h4>
    <div class="form-group {% if form.errors.metadata %}has-error{% endif %}">
    {% if form.errors.metadata %}
    <div class="alert alert-danger">{{form.errors.metadata}}</div>
    {% endif %}
    {{form.metadata}}
    </div>

    <button type="submit" class="btn btn-success btn-block">Save</button>
</form>

<script type="text/javascript">
$(document).ready(function(){
    $('#name').focus();

    var mf_fields_count = $("#metadata_fields .form-group").size()

    function setminus_visibile_on_first_row() {
        var first = $("#metadata_fields .form-group").get(0);
        var btn = $(first).find(".btn-danger");

        console.log(mf_fields_count.toString());
        if (mf_fields_count <= 1) {
            btn.hide();
        } else {
            btn.show();
        }

    }

    function clone_and_clean(element) {
        var obj = element.clone()

        var inputs = $(obj).find("input");
        inputs.each(function(idx, input){
            $(this).val("");
        });


        return obj;
    }

    function prep(container, index, value) {
        var minus = $(container).find('.btn-danger');
        var plus  = $(container).find('.btn-success');

        minus.click(function(){
            $(container).remove();
            mf_fields_count -= 1;
            setminus_visibile_on_first_row();
        });

        plus.click(function(){
            var newrow = clone_and_clean($(container));
            newrow.appendTo($(container).parent());

            mf_fields_count += 1;
            prep(newrow, mf_fields_count-1, "" );
            setminus_visibile_on_first_row();
        });

        if(index == 0) {
            minus.hide();
        } else {
            minus.show();
        }
    }


    $("#metadata_fields .form-group").each(function(index, value){
        var that = $(this);
        prep(that, index, value);
    });
});
</script>

<style>
#id_read_access li   { list-style: none; margin-left: -30px; }
#id_write_access li  { list-style: none; margin-left: -30px; }
#id_edit_access li   { list-style: none; margin-left: -30px; }
#id_delete_access li { list-style: none; margin-left: -30px; }
#id_read_access   { margin-top: 10px; }
#id_write_access  { margin-top: 10px; }
#id_edit_access   { margin-top: 10px; }
#id_delete_access { margin-top: 10px; }
.left-border { border-left: solid 1px #eee; }
</style>

archive/templates/archive/snippets/metadata.html
  {% for m in metadata %}
    {% if m.0|length > 10 or m.1|length > 10 %}
      <span class="label label-{{label}}" data-toggle="tooltip" title="{{ m.0 }} = {{ m.1 }}">
           ...
      </span>&nbsp;&nbsp;
    {% else %}
       <span class="label label-{{label}}">
       {{ m.0 }} = {{ m.1 }}
       </span>&nbsp;&nbsp;
    {% endif %}
  {% endfor %}

archive/templates/archive/snippets/metadata_dropdown.html
<div class="col-md-12">
<a  data-toggle="collapse" href="#{{id}}-collapse" aria-expanded="false" aria-controls="collapseExample">
  <span class="caret"></span> Metadata
</a>
<div class="collapse" id="{{id}}-collapse" style="margin-top:28px;">
  <div class="well">
     {% include "archive/snippets/metadata.html" with metadata=metadata %}
  </div>
</div>
</div>